## Numpy

its a fundamental lib for scientific computing in Python.it provides support for arrays and matrics,along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

## Create array
## 1D
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## 2D
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
##Create 2D array with all elements 1:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##Attributes of numpy
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size(number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Items size (in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Items size (in bytes) 8


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##Element wise Addition
print("Addition",arr1+arr2)

##Element wise Multiplication
print("Multiplication",arr1*arr2)

##Element wise divison
print("Divion",arr1/arr2)

Addition [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Divion [0.1 0.1 0.1 0.1 0.1]


In [21]:
##Universal Function
arr=np.array([2,3,4,5,6])
##Square root
print(np.sqrt(arr))
##Exponential
print(np.exp(arr))
##Sine
print(np.sin(arr))
##Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [2]:
## array slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr[0,0]

np.int64(1)

In [4]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
print(arr[1:,2:])
print(arr[0:2,2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [11]:
## Modify array elements
arr[0,0]=100
arr[1][1]=1222
print(arr)

[[ 100    2    3    4]
 [   5 1222    7    8]
 [   9   10   11   12]]


In [15]:
## Statistical concepts --  Normalization
## to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

mean=np.mean(data)
median=np.median(data)
variance=np.var(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])